# Generated by Django 4.2.1 on 2023-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='menbers',
            new_name='members',
        ),
    ]
